nikor <- new.env()

nikor$lambda <- \(x, f) f(x)
nikor$extract <- .Primitive("[")
nikor$extract2 <- .Primitive("[[")
nikor$times <- .Primitive("*")
nikor$over <- .Primitive("/")
nikor$plus <- .Primitive("+")
nikor$minus <- .Primitive("-")
nikor$raise <- .Primitive("^")
nikor$int_div <- .Primitive("%/%")
nikor$modulo <- .Primitive("%%")

attach(nikor)
rm(nikor)
